import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  textbookSidebar: [
    'intro',
    'schedule',
    {type: 'autogenerated', dirName: 'module-1-ros2'},
    {type: 'autogenerated', dirName: 'module-2-simulation'},
    {type: 'autogenerated', dirName: 'module-3-isaac'},
    {type: 'autogenerated', dirName: 'module-4-vla'},
    {type: 'autogenerated', dirName: 'capstone'},
    {type: 'autogenerated', dirName: 'hardware'},
  ],
};

export default sidebars;
